name: Assign Random Reviewers

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Select random reviewers
        id: get-reviewers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: "2-Docthru-team1"
          REPO: "2-Docthru-team1-BE"
        run: |
          # 고정된 리뷰어 목록 설정
          REVIEWERS=("alscksdlek" "csbizz" "galaxy-78" "ganghoho" "taeyeonkim94")

          # PR 작성자 제외
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          FILTERED_REVIEWERS=()

          for reviewer in "${REVIEWERS[@]}"; do
            if [ "$reviewer" != "$PR_AUTHOR" ]; then
              FILTERED_REVIEWERS+=("$reviewer")
            fi
          done

          # 랜덤하게 2명 선택
          if [ ${#FILTERED_REVIEWERS[@]} -ge 2 ]; then
            selected_reviewers=($(shuf -n 2 -e "${FILTERED_REVIEWERS[@]}"))
            
            # JSON 형식으로 리뷰어 배열 생성
            payload="{\"reviewers\": [\"${selected_reviewers[0]}\", \"${selected_reviewers[1]}\"]}"
            echo "payload=$payload" >> $GITHUB_ENV
            
            echo "Selected reviewers: ${selected_reviewers[*]}"
          else
            echo "Not enough eligible reviewers available"
            exit 1
          fi

      - name: Assign reviewers to PR
        run: |
          echo "${{ env.payload }}" > payload.json
          curl -X POST \
            "https://api.github.com/repos/${{ env.ORGANIZATION }}/${{ env.REPO }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            --data @payload.json
