name: Assign Random Reviewers
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Get team members
        id: get-members
        run: |
          # Get organization and team name from repository
          ORG_NAME="2-Docthru-team1"
          
          # First, get all teams in the organization
          teams=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/${ORG_NAME}/teams")
          
          echo "Available teams: $teams"
          
          # Get the first team's slug (assuming there's at least one team)
          team_slug=$(echo "$teams" | jq -r '.[0].slug')
          
          echo "Team slug: $team_slug"
          
          # Get team members
          members=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/${ORG_NAME}/teams/${team_slug}/members" | jq -r '.[].login')
          
          echo "All members: $members"
          
          # Convert members to array and remove PR author
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          filtered_members=()
          for member in $members; do
            if [ "$member" != "$PR_AUTHOR" ]; then
              filtered_members+=("$member")
            fi
          done
          
          echo "Filtered members: ${filtered_members[*]}"
          
          # Randomly select 2 reviewers
          if [ ${#filtered_members[@]} -lt 2 ]; then
            echo "Not enough members to assign reviewers (excluding PR author)"
            echo "Number of available reviewers: ${#filtered_members[@]}"
            exit 1
          fi
          
          # Shuffle and select 2 reviewers
          selected_reviewers=($(printf "%s\n" "${filtered_members[@]}" | shuf -n 2))
          json_array=$(printf '"%s",' "${selected_reviewers[@]}" | sed 's/,$//')
          
          echo "Selected reviewers: ${selected_reviewers[*]}"
          echo "json_array=$json_array" >> $GITHUB_OUTPUT

      - name: Assign reviewers to PR
        if: success()
        run: |
          curl -X POST \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"reviewers\": [${{ steps.get-members.outputs.json_array }}]}"
